#!/usr/bin/env python3
# -*- coding: utf-8 -*-

import openpyxl
from openpyxl import Workbook
import os
import sys

# 设置输出编码
if sys.platform == 'win32':
    import io
    sys.stdout = io.TextIOWrapper(sys.stdout.buffer, encoding='utf-8')

output_dir = r"E:\jingpengliu_work\Book\English\self-bulid-book2\写作词汇-主题\084国际合作"

# 定义数据 - 使用列表
data_84_1 = [
    ["international organization", "国际组织", "指由多个国家或地区为了共同目标而建立的合作机制。适用语境：讨论全球治理、多边合作等话题。句型结构：join/join an international organization; membership in international organizations。相近表达：global institution, multinational body, international body。使用注意：常与join, establish, member of等动词搭配。", "Many countries have chosen to join international organizations to address global challenges that no single nation can solve alone.", "许多国家选择加入国际组织，以应对任何单一国家都无法独自解决的全球性挑战。"],
    ["multilateral cooperation", "多边合作", "涉及多个国家或参与方的合作形式。适用语境：国际贸易、气候变化、反恐等领域。句型结构：engage in multilateral cooperation; promote multilateral cooperation。相近表达：bilateral cooperation, plurilateral cooperation。使用注意：强调多个行为体之间的合作，是雅思写作中讨论国际关系的常用表达。", "Multilateral cooperation among nations is essential for tackling transnational issues such as climate change and pandemics.", "多边合作对于应对气候变化和流行病等跨国问题至关重要。"],
    ["intergovernmental organization", "政府间组织", "由各国政府创立的国际组织，成员为国家。适用语境：讨论联合国、世界贸易组织等机构。句型结构：establish an intergovernmental organization; work within intergovernmental organizations。相近表达：international agency, international institution。使用注意：更正式的表述，强调组织的政府性质。", "The intergovernmental organization plays a crucial role in coordinating policies across member states.", "该政府间组织在协调成员国政策方面发挥着关键作用。"],
    ["global governance", "全球治理", "国际社会通过规则、制度管理全球事务的过程。适用语境：讨论国际秩序、跨国问题解决。句型结构：improve global governance; challenges to global governance。相近表达：international governance, world governance。使用注意：常与mechanism, system, framework搭配。", "Effective global governance requires the participation and commitment of all major powers.", "有效的全球治理需要主要大国的参与和承诺。"],
    ["treaty", "条约", "国家之间就特定事项达成的正式协议。适用语境：国际法、环境保护、裁军协议等。句型结构：sign/ratify a treaty; violate a treaty; breach of treaty obligations。相近表达：agreement, convention, pact。使用注意：注意动词搭配：sign a treaty（签署）, ratify a treaty（批准）。", "International treaties on climate change require coordinated action from all signatory countries.", "气候变化国际条约要求所有签署国采取协调行动。"],
    ["member state", "成员国", "加入某个国际组织的国家。适用语境：讨论国际组织的成员资格和义务。句型结构：member state of; obligations of member states。相近表达：member country, participating nation。使用注意：常用复数形式member states，强调集体责任。", "All member states are expected to contribute financially to the organization's humanitarian initiatives.", "所有成员国都应该为该组织的人道主义倡议提供资金支持。"],
    ["diplomatic relations", "外交关系", "国家之间的官方交往和联系。适用语境：讨论国际关系正常化、外交政策。句型结构：establish/break off diplomatic relations; maintain diplomatic relations。相近表达：foreign relations, international relations。使用注意：establish diplomatic relations（建交）是常见搭配。", "The two countries decided to establish diplomatic relations after decades of isolation.", "这两个国家在数十年的孤立之后决定建立外交关系。"],
    ["summit", "峰会", "国家领导人或高级官员的高级别会议。适用语境：讨论国际会议、重大决策。句型结构：attend a summit; hold a summit; summit meeting。相近表达：conference, meeting, forum。使用注意：强调高层级、常用于G7、G20等重大国际会议。", "World leaders gathered at the summit to discuss strategies for sustainable development.", "世界各国领导人齐聚峰会，讨论可持续发展战略。"],
    ["ratify", "批准", "正式同意并使条约或协议生效。适用语境：国际协议、法律批准。句型结构：ratify a treaty/an agreement; ratification process。相近表达：approve, endorse, sanction。使用注意：比approve更正式，常用于国际条约语境。", "Parliament voted to ratify the international convention on wildlife protection.", "议会投票批准了野生动物保护国际公约。"],
    ["transnational", "跨国的", "超越国界的、涉及多个国家的。适用语境：讨论跨国问题、全球化影响。句型结构：transnational corporations; transnational issues; transnational cooperation。相近表达：international, global, cross-border。使用注意：强调超越单一国家边界的特性。", "Transnational corporations play an increasingly important role in the global economy.", "跨国公司在全球经济中发挥着越来越重要的作用。"],
    ["alliance", "联盟", "国家之间为了共同利益而形成的正式合作关系。适用语境：军事联盟、政治联盟。句型结构：form an alliance; join an alliance; military alliance。相近表达：coalition, partnership, bloc。使用注意：强调共同防御或进攻的军事/政治合作。", "The military alliance between the two nations has maintained regional stability for decades.", "两国之间的军事联盟几十年来维护了地区稳定。"],
    ["collective security", "集体安全", "通过国际合作维护国际和平与安全的机制。适用语境：讨论国际和平、联合国维和。句型结构：ensure collective security; collective security system。相近表达：mutual security, common security。使用注意：强调通过国际合作而非单边行动确保安全。", "The principle of collective security requires all nations to respond together to threats to peace.", "集体安全原则要求所有国家共同应对和平威胁。"],
    ["affiliate", "附属机构", "与主要组织相连的分支机构或成员组织。适用语境：讨论国际组织的分支结构。句型结构：be affiliated with; affiliate organization。相近表达：subsidiary, branch, chapter。使用注意：常用被动语态，表示隶属于某个组织。", "The research institute is affiliated with the United Nations Educational, Scientific and Cultural Organization.", "该研究所隶属于联合国教科文组织。"],
    ["sovereignty", "主权", "国家对领土和事务的独立自主权力。适用语境：讨论国家独立性、国际法限制。句型结构：national sovereignty; respect sovereignty; infringe on sovereignty。相近表达：independence, autonomy, authority。使用注意：常与respect, violate, challenge等动词搭配。", "International organizations must balance their authority with respect for national sovereignty.", "国际组织必须在尊重国家主权的前提下行使权力。"],
    ["humanitarian intervention", "人道主义干预", "为保护平民而进行的跨国军事或外交行动。适用语境：讨论人权保护、国际冲突。句型结构：humanitarian intervention in; justify humanitarian intervention。相近表达：peacekeeping operation, military intervention。使用注意：是一个有争议的话题，常用于讨论国际法与道德责任。", "The debate over humanitarian intervention remains contentious in international law.", "关于人道主义干预的争论在国际法中仍然存在争议。"],
    ["charter", "宪章", "组织的基本章程或纲领性文件。适用语境：讨论国际组织的基本原则。句型结构：the charter of; charter member; violate the charter。相近表达：constitution, manifesto, statute。使用注意：尤指国际组织的founding document。", "All member states are bound by the principles outlined in the organization's charter.", "所有成员国都受到该组织宪章所列原则的约束。"],
    ["mandate", "授权", "正式授权或委托执行某项任务。适用语境：讨论国际组织的职责和权限。句型结构：under the mandate of; carry out a mandate; expand the mandate。相近表达：authorization, commission, authority。使用注意：常用词组under the mandate of表示在...的授权下。", "The peacekeepers are operating under the mandate of the United Nations Security Council.", "维和人员在联合国安理会的授权下执行任务。"],
    ["liaison", "联络", "不同组织或国家之间的联系渠道。适用语境：讨论国际合作渠道、外交联系。句型结构：establish liaison; liaison officer; liaison committee。相近表达：contact, connection, bridge。使用注意：强调不同方之间的沟通协调作用。", "The organization established a liaison office to coordinate efforts with local authorities.", "该组织设立了联络处，以与地方当局协调工作。"],
    ["protocol", "议定书", "条约的补充协议或正式程序。适用语境：国际协议、正式程序。句型结构：sign a protocol; follow protocol; diplomatic protocol。相近表达：agreement, convention, guidelines。使用注意：有时指外交礼仪或正式程序。", "The附加议定书 sets out specific obligations for member states regarding emissions reduction.", "附加议定书规定了成员国在减排方面的具体义务。"],
    ["framework", "框架", "组织或处理问题的基本结构或体系。适用语境：讨论国际合作机制、政策框架。句型结构：legal framework; framework for cooperation; establish a framework。相近表达：structure, system, mechanism。使用注意：常与legal, policy, cooperation搭配。", "The framework provides a structured approach for countries to address shared environmental challenges.", "该框架为各国解决共同的环境挑战提供了结构化的方法。"]
]

data_84_2 = [
    ["United Nations", "联合国", "成立于1945年的国际组织，旨在维护世界和平与发展。适用语境：讨论国际合作、维和行动、全球治理。句型结构：the United Nations; UN peacekeeping; UN agencies。相近表达：the UN, the world organization。使用注意：常用缩写UN，注意与the搭配。", "The United Nations has played a pivotal role in mediating conflicts and promoting international cooperation.", "联合国在调解冲突和促进国际合作方面发挥了关键作用。"],
    ["Security Council", "安理会", "联合国负责维护国际和平与安全的机构。适用语境：讨论维和行动、国际制裁、重大决议。句型结构：the Security Council; UN Security Council; Security Council resolution。相近表达：the UNSC, the Security Council of the UN。使用注意：拥有五常否决权，是联合国最重要的决策机构。", "The Security Council has the authority to impose sanctions and authorize military intervention.", "安理会拥有实施制裁和授权军事干预的权力。"],
    ["General Assembly", "联合国大会", "联合国的主要审议机构，所有成员国参与。适用语境：讨论国际议题、投票表决。句型结构：the General Assembly; address the General Assembly; General Assembly resolution。相近表达：the UNGA, the plenary assembly。使用注意：每年召开常会，是各国表达立场的重要平台。", "The General Assembly provides a forum for all member states to discuss global issues.", "联合国大会为所有成员国提供了讨论全球问题的论坛。"],
    ["peacekeeping", "维和行动", "联合国派遣部队维持冲突地区和平的行动。适用语境：讨论国际冲突解决、人道主义救援。句型结构：UN peacekeeping; peacekeeping mission; peacekeeping forces。相近表达：peace enforcement, conflict prevention, peacekeeping operations。使用注意：强调keeping而非enforcing，以观察员和缓冲部队为主。", "UN peacekeeping missions have been deployed to various conflict zones around the world.", "联合国维和行动已被部署到世界各地的各个冲突地区。"],
    ["resolution", "决议", "国际组织通过的正式决定。适用语境：讨论国际决策、法律效力。句型结构：adopt a resolution; violate a resolution; Security Council resolution。相近表达：decision, ruling, decree。使用注意：联合国决议具有不同的约束力水平。", "The Security Council adopted a resolution condemning the use of chemical weapons.", "安理会通过了一项谴责使用化学武器的决议。"],
    ["humanitarian aid", "人道主义援助", "对受冲突或灾难影响地区提供的紧急援助。适用语境：讨论国际援助、自然灾害应对。句型结构：provide humanitarian aid; humanitarian aid organizations; humanitarian crisis。相近表达：relief assistance, emergency aid, disaster relief。使用注意：强调中立的、非政治化的人道救援。", "Humanitarian aid organizations work tirelessly to provide food, shelter, and medical care to those in need.", "人道主义援助组织不知疲倦地为需要帮助的人提供食物、住所和医疗护理。"],
    ["development goals", "发展目标", "国际社会设定的社会发展与经济进步目标。适用语境：讨论国际发展议程、减贫策略。句型结构：achieve development goals; sustainable development goals; development goals。相近表达：objectives, targets, milestones。使用注意：常与Sustainable搭配，形成SDG（可持续发展目标）。", "The international community has committed to achieving sustainable development goals by 2030.", "国际社会承诺在2030年前实现可持续发展目标。"],
    ["veto power", "否决权", "安理会常任理事国阻止决议通过的特殊权力。适用语境：讨论大国政治、国际决策机制改革。句型结构：exercise veto power; veto power of the permanent members; veto a resolution。相近表达：blocking power, negative vote。使用注意：仅五常拥有，是国际政治中的重要议题。", "The use of veto power by permanent members often leads to deadlocks in the Security Council.", "常任理事国使用否决权往往导致安理会陷入僵局。"],
    ["secretariat", "秘书处", "联合国的行政机构，负责日常运作。适用语境：讨论国际组织运作、执行决策。句型结构：the UN Secretariat; Secretariat of; head of the secretariat。相近表达：the administrative body, the executive arm。使用注意：联合国秘书长是秘书处最高负责人。", "The Secretariat implements decisions made by the Security Council and General Assembly.", "秘书处执行安理会和大会做出的决定。"],
    ["human rights", "人权", "人人生而享有的基本权利和自由。适用语境：讨论国际人权保护、普世价值。句型结构：human rights violations; human rights protection; human rights council。相近表达：fundamental rights, civil liberties, basic freedoms。使用注意：常与protect, violate, promote搭配。", "The UN Human Rights Council works to promote and protect fundamental freedoms worldwide.", "联合国人权理事会致力于在全球范围内促进和保护基本自由。"],
    ["refugee", "难民", "因战争、冲突或迫害逃离本国的人。适用语境：讨论移民问题、人道主义危机。句型结构：refugee crisis; refugee camps; refugee status。相近表达：asylum seeker, displaced person, refugee。使用注意：严格定义包括well-founded fear of persecution。", "The UNHCR provides protection and assistance to refugees fleeing conflict zones.", "联合国难民署为逃离冲突地区的难民提供保护和援助。"],
    ["sanctions", "制裁", "对违反国际法的国家采取的惩罚性措施。适用语境：讨论国际惩罚、经济压力。句型结构：impose sanctions; economic sanctions; lift sanctions。相近表达：penalties, restrictions, embargoes。使用注意：常用复数形式，常与impose, lift, ease搭配。", "International sanctions are often used as a diplomatic tool to pressure countries to change their policies.", "国际制裁常被用作向各国施压以改变政策的外交工具。"],
    ["mediation", "调解", "第三方帮助冲突各方达成和解的过程。适用语境：讨论国际冲突解决、和平谈判。句型结构：offer mediation; mediation efforts; peace mediation。相近表达：negotiation, arbitration, conciliation。使用注意：强调第三方协助而非强制。", "The UN Secretary-General offered mediation to help end the prolonged conflict.", "联合国秘书长提供调解帮助，以结束这场旷日持久的冲突。"],
    ["trustee", "托管", "联合国对特定地区进行暂时管理的制度。适用语境：讨论国际托管、领土管理。句型结构：trust territory; trusteeship council; under trusteeship。相近表达：custodianship, guardianship, administration。使用注意：现存的托管领土已大多独立或自治。", "The Trusteeship Council was established to supervise the administration of trust territories.", "托管理事会成立的目的在于监督托管领土的管理。"],
    ["multilingualism", "多语言制", "在联合国等国际组织中使用多种官方语言。适用语境：讨论语言平等、文化多样性。句型结构：multilingualism in the UN; promote multilingualism; multilingual policy。相近表达：polyglotism, linguistic diversity。使用注意：联合国六种官方语言：英、法、西、俄、中、阿拉伯。", "Multilingualism is fundamental to ensuring equal participation of all member states in UN proceedings.", "多语言制对于确保所有成员国在联合国 proceedings 中平等参与至关重要。"],
    ["disarmament", "裁军", "减少或消除军事武装的国际努力。适用语境：讨论核裁军、军备控制。句型结构：nuclear disarmament; arms control and disarmament; disarmament negotiations。相近表达：arms reduction, demilitarization。使用注意：是一个持续的国际议题，尤其涉及核武器。", "International disarmament efforts have focused on preventing the proliferation of nuclear weapons.", "国际裁军努力集中于防止核武器扩散。"],
    ["sustainable development", "可持续发展", "满足当前需求而不损害未来世代的发展模式。适用语境：讨论环境保护、经济发展、国际合作。句型结构：sustainable development; promote sustainable development; sustainable development goals。相近表达：sustainable growth, responsible development。使用注意：常与economic, social, environmental搭配形成三重底线。", "The UN has prioritized sustainable development as a key goal for the international community.", "联合国将可持续发展作为国际社会的关键目标。"],
    ["negotiate", "谈判", "通过讨论达成协议的过程。适用语境：讨论国际协议、和平进程。句型结构：negotiate an agreement; peace negotiations; negotiate with。相近表达：discuss, bargain, confer。使用注意：常用词组negotiate with sb. about/on/over sth.。", "The two governments agreed to negotiate a peaceful settlement to the border dispute.", "两国政府同意通过谈判和平解决边界争端。"],
    ["conflict resolution", "冲突解决", "通过和平手段结束或防止武装冲突。适用语境：讨论国际和平、调解机制。句型结构：conflict resolution mechanism; peaceful conflict resolution; conflict resolution process。相近表达：dispute settlement, peacebuilding。使用注意：强调和平、非暴力手段。", "International organizations play a vital role in conflict resolution through mediation and dialogue.", "国际组织通过调解和对话在冲突解决中发挥关键作用。"],
    ["decolonization", "非殖民化", "殖民地获得独立的过程。适用语境：讨论历史进程、国际自决。句型结构：decolonization process; decolonization of; wave of decolonization。相近表达：independence, liberation, self-determination。使用注意：20世纪中后期大规模非殖民化运动。", "The decolonization process of the 20th century led to the emergence of many new independent nations.", "20世纪的去殖民化进程导致许多新的独立国家出现。"]
]

data_84_3 = [
    ["foreign aid", "外国援助", "一国向其他国家提供的经济或技术援助。适用语境：讨论国际发展、贫困国家支持。句型结构：provide foreign aid; receive foreign aid; foreign aid package。相近表达：international aid, external assistance, overseas aid。使用注意：常用语国际发展讨论，是雅思写作经济类话题的高频词。", "Many developed countries have pledged to increase foreign aid to developing nations.", "许多发达国家承诺增加对发展中国家的外国援助。"],
    ["development assistance", "发展援助", "帮助发展中国家实现经济社会发展的支持。适用语境：讨论国际发展合作、减贫策略。句型结构：development assistance; provide development assistance; development assistance programs。相近表达：development aid, development support, aid。使用注意：强调长期发展目标，而非短期救济。", "Development assistance from wealthy nations can help alleviate poverty in less developed countries.", "富裕国家的发展援助可以帮助减轻欠发达国家的贫困。"],
    ["economic development", "经济发展", "国家经济状况的改善和增长。适用语境：讨论国际发展、减贫、经济增长。句型结构：promote economic development; hinder economic development; economic development strategies。相近表达：economic growth, economic progress, economic advancement。使用注意：强调可持续性和包容性。", "International organizations work to promote economic development in developing countries.", "国际组织致力于促进发展中国家的经济发展。"],
    ["poverty alleviation", "减贫", "减少或消除贫困的努力。适用语境：讨论国际发展、社会问题。句型结构：poverty alleviation; alleviate poverty; poverty alleviation programs。相近表达：poverty reduction, poverty eradication, poverty relief。使用注意：alleviation强调减轻，eradication强调彻底消除。", "Poverty alleviation remains one of the primary goals of international development efforts.", "减贫仍然是国际发展努力的主要目标之一。"],
    ["capacity building", "能力建设", "帮助发展中国家提升自身能力的援助形式。适用语境：讨论国际援助的有效性、可持续发展。句型结构：capacity building; capacity building program; build capacity。相近表达：capacity development, capability enhancement。使用注意：强调帮助受援国自我发展，而非依赖外部援助。", "International donors should focus on capacity building to ensure sustainable development outcomes.", "国际援助方应注重能力建设，以确保可持续发展成果。"],
    ["infrastructure", "基础设施", "国家发展所必需的基础设施系统。适用语境：讨论经济发展条件、援助重点。句型结构：infrastructure development; infrastructure projects; critical infrastructure。相近表达：public facilities, basic facilities, physical infrastructure。使用注意：常与build, develop, improve搭配。", "Foreign investment in infrastructure can accelerate economic growth in developing countries.", "外国对基础设施的投资可以加速发展中国家的经济增长。"],
    ["debt relief", "债务减免", "减少或免除发展中国家债务的措施。适用语境：讨论国际金融、发展中国家负担。句型结构：debt relief; provide debt relief; debt relief program。相近表达：debt cancellation, debt reduction, debt forgiveness。使用注意：是国际发展讨论中的重要议题。", "Debt relief can free up resources for developing countries to invest in health and education.", "债务减免可以释放资源，让发展中国家投资于医疗和教育。"],
    ["technical assistance", "技术援助", "提供专业知识和技术支持的国际援助。适用语境：讨论知识转移、能力建设。句型结构：provide technical assistance; technical assistance program; technical assistance mission。相近表达：technical support, expertise, know-how transfer。使用注意：强调知识和技能的转移。", "Technical assistance from developed countries helps developing nations build institutional capacity.", "发达国家提供的技术援助帮助发展中国家建立制度能力。"],
    ["grant", "赠款", "无需偿还的财政援助。适用语境：讨论国际援助形式、资金支持。句型结构：provide a grant; grant funding; research grant。相近表达：donation, contribution, subsidy。使用注意：与loan（贷款）相对，无需偿还。", "Many countries receive grants from international organizations to fund development projects.", "许多国家从国际组织获得赠款，为发展项目提供资金。"],
    ["loan", "贷款", "需要偿还的资金援助形式。适用语境：讨论国际融资、发展金融。句型结构：provide a loan; concessional loan; repay a loan。相近表达：credit, financing, borrowing。使用注意：常与concessional（优惠）搭配形成优惠贷款。", "Low-interest loans from development banks support infrastructure projects in poorer countries.", "开发银行提供的低息贷款支持较贫穷国家的基础设施项目。"],
    ["food security", "粮食安全", "所有人都能获得足够食物的状态。适用语境：讨论饥饿问题、发展目标。句型结构：achieve food security; food security crisis; food security program。相近表达：food safety, food availability。使用注意：强调长期、稳定的食物供应。", "International aid programs aim to improve food security in regions affected by drought and conflict.", "国际援助项目旨在改善受干旱和冲突影响地区的粮食安全。"],
    ["healthcare system", "医疗体系", "提供医疗服务的整体系统。适用语境：讨论公共卫生、国际援助重点。句型结构：improve healthcare system; healthcare system reform; strengthen healthcare system。相近表达：health system, medical system, health service。使用注意：常用动词build, improve, strengthen搭配。", "International health organizations work to strengthen healthcare systems in developing countries.", "国际卫生组织致力于加强发展中国家的医疗体系。"],
    ["education system", "教育体系", "提供教育的整体制度和结构。适用语境：讨论人才培养、发展投资。句型结构：improve education system; education system reform; access to education。相近表达：educational system, schooling system。使用注意：常用access to education表示受教育机会。", "Foreign aid can help improve the education system in developing countries by building schools and training teachers.", "外国援助可以通过建设学校和培训教师来改善发展中国家的教育体系。"],
    ["urbanization", "城市化", "人口向城市集中的过程。适用语境：讨论城市发展、社会变迁。句型结构：rapid urbanization; urbanization process; urbanization rate。相近表达：urban growth, urban development。使用注意：是发展中国家面临的重大挑战。", "Rapid urbanization in developing countries creates both opportunities and challenges for governments.", "发展中国家的快速城市化给政府带来机遇和挑战。"],
    ["rural development", "农村发展", "改善农村地区经济和社会状况的努力。适用语境：讨论城乡差距、扶贫策略。句型结构：rural development; rural development programs; promote rural development。相近表达：rural advancement, rural improvement。使用注意：常与urban对比使用。", "International development agencies prioritize rural development to reduce poverty and inequality.", "国际发展机构将农村发展作为减少贫困和不平等的优先事项。"],
    ["empowerment", "赋能", "赋予个人或社区权力和能力的做法。适用语境：讨论发展目标、社区建设。句型结构：community empowerment; women's empowerment; empower local communities。相近表达：enabling, capacity enhancement, authorization。使用注意：强调赋予自主权和决策能力。", "Sustainable development requires the empowerment of local communities to take ownership of their future.", "可持续发展需要赋予地方社区对其未来的自主权。"],
    ["international donor", "国际援助方", "提供国际援助的国家或组织。适用语境：讨论援助国、发展合作。句型结构：major international donor; donor countries; donor organizations。相近表达：aid donor, development partner, benefactor。使用注意：常用复数形式donors，强调援助提供方。", "International donors often condition aid on reforms in governance and human rights.", "国际援助方往往将援助与治理和人权改革挂钩。"],
    ["recipient country", "受援国", "接受国际援助的国家。适用语境：讨论援助关系、发展合作。句型结构：recipient country; aid recipient; recipient nations。相近表达：beneficiary country, developing nation。使用注意：强调援助的接受方。", "Recipient countries should be encouraged to take ownership of development projects.", "应该鼓励受援国对发展项目拥有自主权。"],
    ["aid dependency", "援助依赖", "过度依赖外部援助的状态。适用语境：讨论援助有效性、发展可持续性。句型结构：aid dependency; reduce aid dependency; avoid aid dependency。相近表达：aid reliance, dependence on assistance。使用注意：是发展援助讨论中的批评观点。", "Long-term aid programs should aim to reduce aid dependency in developing countries.", "长期援助项目应该旨在减少发展中国家的援助依赖。"],
    ["sustainability", "可持续性", "长期维持而不耗尽资源的能力。适用语境：讨论发展模式、援助效果。句型结构：sustainability; ensure sustainability; environmental sustainability。相近表达：viability, durability, permanence。使用注意：是发展援助中的核心概念。", "Projects should be designed with sustainability in mind to ensure long-term benefits.", "项目设计应考虑可持续性以确保长期效益。"]
]

data_84_4 = [
    ["armed conflict", "武装冲突", "使用武力的国家间或国内暴力冲突。适用语境：讨论战争、暴力、国际安全。句型结构：armed conflict; resolve armed conflict; armed conflict zone。相近表达：military conflict, war, hostilities。使用注意：强调使用武器的暴力冲突。", "Armed conflicts have caused immense human suffering and displaced millions of people.", "武装冲突造成了巨大的人类苦难，使数百万人流离失所。"],
    ["war", "战争", "国家之间或国内的大规模武装冲突。适用语境：讨论军事冲突、和平与安全。句型结构：world war; civil war; declare war。相近表达：battle, combat, warfare。使用注意：是讨论国际冲突的核心词汇。", "The devastating consequences of war highlight the importance of peaceful conflict resolution.", "战争的毁灭性后果凸显了和平解决冲突的重要性。"],
    ["civil war", "内战", "国内不同派系或族群之间的武装冲突。适用语境：讨论国内冲突、国家分裂。句型结构：civil war; outbreak of civil war; end of civil war。相近表达：internal conflict, domestic war, internal warfare。使用注意：区别于international war（国际战争）。", "Civil wars often result in long-term instability and humanitarian crises.", "内战往往导致长期不稳定和人道主义危机。"],
    ["tension", "紧张关系", "国家或群体之间的紧张状态。适用语境：讨论国际关系、潜在冲突。句型结构：political tension; ease tension; tension between。相近表达：strain, friction, hostility。使用注意：常与ease, reduce, alleviate搭配表示缓解。", "Diplomatic negotiations are essential to reduce tensions between rival nations.", "外交谈判对于缓解敌对国家之间的紧张关系至关重要。"],
    ["military intervention", "军事干预", "使用军事力量介入他国或地区事务。适用语境：讨论国际冲突解决、人道主义危机。句型结构：military intervention; justify military intervention; oppose military intervention。相近表达：armed intervention, military involvement, invasion。使用注意：是一个有争议的话题。", "Military intervention without international approval can violate principles of national sovereignty.", "未经国际批准进行的军事干预可能违反国家主权原则。"],
    ["territorial dispute", "领土争端", "两国或多国对同一领土的主权争议。适用语境：讨论边界问题、国际冲突。句型结构：territorial dispute; resolve territorial dispute; territorial conflict。相近表达：border dispute, territorial conflict, land dispute。使用注意：是国际冲突的常见原因。", "Territorial disputes between neighboring countries often require international mediation.", "邻国之间的领土争端通常需要国际调解。"],
    ["aggression", "侵略", "使用武力攻击或威胁他国的行为。适用语境：讨论战争罪、国际法。句型结构：military aggression; act of aggression; condemn aggression。相近表达：attack, invasion, assault。使用注意：是国际法中严厉谴责的行为。", "International law strongly condemns any form of aggression by one nation against another.", "国际法强烈谴责任何形式的侵略行为。"],
    ["ceasefire", "停火", "冲突各方同意停止战斗的协议。适用语境：讨论和平进程、冲突结束。句型结构：ceasefire agreement; declare a ceasefire; observe a ceasefire。相近表达：truce, armistice, cessation of hostilities。使用注意：是和平谈判的第一步。", "The ceasefire allowed humanitarian organizations to deliver aid to civilians in the conflict zone.", "停火使人道主义组织能够向冲突地区的平民提供援助。"],
    ["negotiation", "谈判", "各方通过讨论达成协议的过程。适用语境：讨论和平解决、国际协议。句型结构：peace negotiation; enter into negotiation; conduct negotiation。相近表达：talks, discussions, dialogue。使用注意：常与peace, diplomatic搭配。", "Peace negotiations between the conflicting parties have resumed after a brief interruption.", "冲突各方之间的和平谈判在短暂中断后已经恢复。"],
    ["reconciliation", "和解", "冲突各方恢复友好关系的过程。适用语境：讨论和平进程、战后重建。句型结构：reconciliation process; national reconciliation; achieve reconciliation。相近表达：reunion, settlement, harmonization。使用注意：强调长期的和平与信任重建。", "Reconciliation is essential for lasting peace in regions affected by prolonged conflict.", "和解对于长期受冲突影响的地区实现持久和平至关重要。"],
    ["refugee crisis", "难民危机", "大量难民流动造成的紧急状况。适用语境：讨论人道主义危机、国际援助。句型结构：refugee crisis; handle refugee crisis; worsen refugee crisis。相近表达：migration crisis, displacement crisis。使用注意：是当代国际冲突的重要后果。", "The refugee crisis resulting from the conflict has strained resources in neighboring countries.", "冲突导致的难民危机使邻国资源紧张。"],
    ["proxy war", "代理战争", "大国通过第三方进行的间接战争。适用语境：讨论国际政治、超级大国竞争。句型结构：proxy war; fight a proxy war; proxy war in。相近表达：indirect conflict, surrogate war。使用注意：强调背后大国的操控。", "The proxy war in the region has prolonged the suffering of local civilians.", "该地区的代理战争延长了当地平民的痛苦。"],
    ["genocide", "种族灭绝", "有系统地消灭某一民族、种族或宗教群体的行为。适用语境：讨论战争罪、反人类罪。句型结构：act of genocide; genocide prevention; commit genocide。相近表达：mass slaughter, ethnic cleansing, extermination。使用注意：是国际法中最严重的罪行之一。", "The international community has a responsibility to prevent genocide and crimes against humanity.", "国际社会有责任防止种族灭绝和反人类罪。"],
    ["occupation", "占领", "军事力量控制他国领土的行为。适用语境：讨论领土争议、国际法。句型结构：military occupation; under occupation; end the occupation。相近表达：invasion, annexation, control。使用注意：通常是非法的、临时的军事控制。", "Foreign occupation often generates resistance and resentment among the local population.", "外国占领往往在当地居民中引起抵抗和怨恨。"],
    ["disarmament", "裁军", "减少或消除军事武装。适用语境：讨论和平进程、国际安全。句型结构：nuclear disarmament; disarmament talks; disarmament process。相近表达：arms reduction, demilitarization。使用注意：是国际和平努力的重要组成部分。", "Nuclear disarmament remains a critical goal for international peace and security.", "核裁军仍然是国际和平与安全的关键目标。"],
    ["ethnic conflict", "民族冲突", "不同民族或族群之间的暴力冲突。适用语境：讨论国内冲突、民族问题。句型结构：ethnic conflict; resolve ethnic conflict; ethnic violence。相近表达：ethnic tension, ethnic strife, communal violence。使用注意：是许多国家内部冲突的根源。", "Ethnic conflicts often have deep historical roots and are difficult to resolve peacefully.", "民族冲突往往有深厚的历史根源，难以和平解决。"],
    ["treaty", "条约", "国家之间就和平或其他事项达成的正式协议。适用语境：讨论国际协议、战争结束。句型结构：peace treaty; sign a treaty; violate a treaty。相近表达：agreement, accord, pact。使用注意：和平条约通常结束战争状态。", "The peace treaty ended decades of hostilities between the two nations.", "和平条约结束了两国之间数十年的敌对状态。"],
    ["war crime", "战争罪", "违反战争法规的严重罪行。适用语境：讨论国际法、责任追究。句型结构：war crime; commit war crimes; war crimes tribunal。相近表达：violation of humanitarian law, atrocities。使用注意：国际刑事法院管辖的罪行。", "Those responsible for war crimes should be held accountable through international justice.", "应对战争罪责任人通过国际司法追究责任。"],
    ["neutrality", "中立", "在冲突中不站在任何一方的立场。适用语境：讨论国际法、外交政策。句型结构：maintain neutrality; violate neutrality; neutrality in conflict。相近表达：non-alignment, impartiality, neutrality。使用注意：是国际法承认的地位。", "Neutral countries can play a valuable role in mediating conflicts and providing humanitarian aid.", "中立国家可以在调解冲突和提供人道主义援助方面发挥宝贵作用。"],
    ["peace process", "和平进程", "实现和平的逐步过程和步骤。适用语境：讨论冲突解决、和平谈判。句型结构：peace process; advance the peace process; derail the peace process。相近表达：peace talks, peace negotiations, peace effort。使用注意：强调逐步的、长期的和平努力。", "The peace process requires commitment from all parties involved to achieve lasting resolution.", "和平进程需要所有相关方的承诺才能实现持久的解决方案。"]
]

def save_to_excel(data, filename):
    wb = Workbook()
    ws = wb.active
    for row in data:
        ws.append(row)
    wb.save(filename)
    print(f"Done: {filename}")

# Save all files
save_to_excel(data_84_1, os.path.join(output_dir, "84.1 国际组织.xlsx"))
save_to_excel(data_84_2, os.path.join(output_dir, "84.2 联合国.xlsx"))
save_to_excel(data_84_3, os.path.join(output_dir, "84.3 国际援助.xlsx"))
save_to_excel(data_84_4, os.path.join(output_dir, "84.4 国际冲突.xlsx"))

print("All files generated successfully!")
